install.md

Added comment for tlmgr needing sudo on OSX.

---

links.md

I added a link to my my personal favourite editor Visual Studio Code, to the links list.

Editor alternative

---

index.md

We split up numpy and scipy to get faster to the fun part

Switch matplotlib and scipy in timetable

---

index.md

Update main page

---

_data/navigation.yml
_includes/header.html
_layouts/category-custom.html
_layouts/category.html
_layouts/default.html
_layouts/post.html
about.md
blog/index.md
css/custom.css
faq/index.md

Setup website to have a blog and an faq section using jekyll posts, no posts yet

Add blog and faq

---

_includes/header.html
css/custom.css

* Navbar was collapsing to fast for my tase, switching on md should be fine
* Code highligh lost it's gray background, I think having it is better to make out commands that should be entered

Fix style after bootstrap update

---

install/macos.md

update Anaconda link
add VS Code + Latex plugin
add VS Code to PATH
set VS Code as git editor

update mac install

---

install/windows.md

This lead to problems on *some* windows 10 pcs. WTF

Use $HOME instead of ~

---

about.md
index.md

Daten und Hörsall in Tabelle
Neue Umfragen
weiterer Veranstalter

Anpassung an Toolbox 2019

---

index.md

entsprechend der Rückmeldung der zentralen Raumvergabe.

Änderung des Hörsaales am 01.10 und 02.10.

---

install/linux.md

- added point to install the linux version of anaconda
- changed the name to the recent namestyle

Small changes for Anaconda on Linux-Systems

---

index.md

10 people wanted to attend the avtivity monday morning

Added an extra date for installation process

---

index.md

ergänzen der 'Anmeldung' per Mail

Betreutes Installieren am Freitag

---

index.md

wrote an email to the two students who showed interest

deleted the date for installation on friday

---

index.md

& modified program names to their way of spelling

changed the timetable

---

install/windows.md

+ removed some redundant passages
+ added references to other sections where appropriate
+ improved upon the trouble-shooting section

Fixes windows installation

---

install/linux.md

put both tlmgr commands after the tex installation part

added instruction for eduroam to linux installation notes

---

notes.md

add exercises day 5 19

---

notes.md

add exercises day 4

---

install/linux.md
install/windows.md

TeXLive 2020 and Anaconda 2020.02 released
Related to #93

Update to TeXLive and Anaconda 2020

---

archive.md
index.md
install/dualboot.md
install/index.md
install/linux.md
notes.md

- Daten auf der Main geändert
- Dateien von 2019 auf Archiv-Seite
- neue Umfragen erstellt und eingebunden
- dualboot: Daten auf 20.04, Hinweise zu Acer-Laptops
- dualboot dieses Jahr generell schwieriger
- unix install: anaconda Namen und luatex Ausgabe erneuert
~~# Noch nicht mergen, genaue Daten und Zoom-Links fehlen~~

2020 Änderung der Daten, noch kein festes Datum bekannt.

---

archive.md

PS: Danke für den (vor langer Zeit) nicen Workshop :)

Fix typo in archive

---

index.md

changed times week 2

---

README.md

- `libxslt-dev` -> `libxslt1-dev`
- added `build-essential` for WSL
- changed bundle installtion according to warnings

changed installation instructions

---

install/linux.md
install/macos.md
install/windows.md

changed anaconda link
changed year for texlive path

Update of years in installation notes

---

about.md
archive.md
index.md
notes.md
problem.md

changed Email list

---

install/windows.md

explain why so long
terminal default through settings #131

windows install

---

install/windows.md

fixed missing `class="screenshot"`

added screenshot class

---

about.md
index.md

clarified digital workshop
#145 & # 146

changed organization

---

README.md

changed from travis to github badge

Ubuntu package change in README

---

_includes/head.html
_includes/header.html
_layouts/default.html
css/custom.css

In my opinion it would be nice to converge Physikon, Toolbox and the main hompage into one design.
The main homepage is quite different in terms of fonts and design decisions but the toolbox and physikon layouts are very similar.
These fixes on the navbar are some easy ones which move the layouts closer to each other.

Change navbar to same design as Physikon homepage

---

install/latex_mini.md
install/linux.md
install/macos.md
install/windows-11.md
install/windows.md

A merge (29e0dcd1d1e4010a82a2ffe4bc885bca8cf6574f) undid some of my corrections.
Now they are back and even stronger! ;)
Previous PR: #190

Fix grammar/typos (2)

---

install/linux.md
install/windows-11.md
install/windows.md

2022 latex windows bashrc

---

_layouts/install.html
css/custom.css
install/dualboot.md
install/latex_mini.md
install/linux.md
install/macos.md
install/windows-11.md
install/windows.md

Add a floating help button to the installation instruction pages (Closes #238).

Floating help button (Closes  #238)

---

_layouts/install.html
css/custom.css

Just some minor tweaks to make the button a bit more appealing.

Update help button design

---

css/custom.css

Use fontawesome chevron up for backtotop button

---

css/custom.css

Improve the help button by displaying "Hilfe" on hover

Improve help button

---

install/dualboot.md

Update the Kubuntu image download URL to the Kubuntu 23.04 image. Old URL is obsolete.

Update kubuntu image download url

---

install/downloads/latex_packages.txt

Fixing Issue #252 
Updating Mini-LaTeX package list

Minilatex package fix

---

about.md
faq/index.md
index.md
install/dualboot.md
install/linux.md
install/macos.md
links.md
notes.md

I am not sure how to proceed with the links I commented in `links.md`.

Links in new tabs

---

archive.md

Fix archive links

---

install/latex_mini.md
install/linux.md
install/macos.md
install/windows-10.md
install/windows-11.md

Update version from 2023 to 2024, e.g. in the PATH export

Update texlive version

---

README.md

add fedora install section

---

_includes/admonition.html
_includes/head.html
css/admonition.css
css/custom.css
install/linux.md
install/macos.md
install/windows-10.md
install/windows-11.md

Adds admonitions to the install instructions:

Admonitions

---

links.md

Should we remove the commented links or hope that they will work again at one point?

add links for template and remove non cuntioning links

---

.github/workflows/build.yml
.github/workflows/deploy.yml

remove duplicate build and verify run

---

install/linux.md
install/macos.md

- Adds updated message after miniforge installation process
- Adds full message for macos installation instructions

Update mamba install
